spring:
  datasource.url: jdbc:mysql://localhost:3306/StudentNutrition?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
  datasource.username: root
  datasource.password: 12345.asdfg
  datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf.cache: false